name: Deploy Agroclime to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-backend-and-frontend:
    name: Configure EC2 and Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create majorproject.pem from secret
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > majorproject.pem
          chmod 400 majorproject.pem

      - name: Update Node.js to v20
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i majorproject.pem ec2-user@$EC2_PUBLIC_IP "curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash - && sudo yum install -y nodejs"

      - name: Install Dependencies and Configure Nginx
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i majorproject.pem ec2-user@$EC2_PUBLIC_IP << 'EOF'
          sudo yum update -y
          sudo yum install -y nginx
          sudo npm install -g pm2
          sudo systemctl start nginx
          sudo systemctl enable nginx
          EOF

      - name: Create Application Directories on EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i majorproject.pem ec2-user@$EC2_PUBLIC_IP "mkdir -p /home/ec2-user/backend"

      - name: Copy Project Files to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          scp -i majorproject.pem -r ./backend ./css ./images ./js ./about.html ./contact.html ./courses.html ./home.html ./login.html ./playlist.html  ./playlist2.html ./playlist3.html ./playlist4.html ./playlist5.html ./playlist6.html ./profile.html ./register.html ./teacher_profile.html ./teachers.html ./update.html ./watch-video.html  ./watch2.html ./watch3.html ./watch4.html ./watch5.html ./watch6.html ./watch7.html ./watch8.html ./watch9.html ./watch10.html ./watch11.html ./watch12.html ./Jenkinsfile ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/backend

      - name: Install Backend Dependencies and Fix Vulnerabilities
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i majorproject.pem ec2-user@$EC2_PUBLIC_IP << 'EOF'
          cd /home/ec2-user/backend
          npm install
          npm audit fix --force || true
          EOF

      - name: Start Backend Application
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i majorproject.pem ec2-user@$EC2_PUBLIC_IP << 'EOF'
          cd /home/ec2-user/backend
          pm2 delete server || true
          pm2 start server.js --name server
          EOF

      - name: Configure Nginx to Serve Application
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i majorproject.pem ec2-user@$EC2_PUBLIC_IP << 'EOF'
          sudo bash -c 'cat > /etc/nginx/nginx.conf' << 'NGINX'
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              include       /etc/nginx/mime.types;
              default_type  application/octet-stream;

              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';

              access_log  /var/log/nginx/access.log  main;

              sendfile        on;
              keepalive_timeout  65;
              include /etc/nginx/conf.d/*.conf;

              server {
                  listen 80;
                  server_name _;

                  location / {
                      proxy_pass http://127.0.0.1:3000;
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection 'upgrade';
                      proxy_set_header Host $host;
                      proxy_cache_bypass $http_upgrade;
                  }

                  location /frontend/ {
                      root /home/ec2-user/backend;
                      index home.html;
                  }
              }
          }
          NGINX
          sudo nginx -t
          sudo systemctl restart nginx
          EOF

      - name: Remove majorproject.pem
        if: always()
        run: |
          rm -f majorproject.pem
